language: go
go:
  - "1.11.x"
  - "1.12.x"
env:
  global:
    - GO111MODULE=on
matrix:
  include:
    - go: "1.13.x"
      install:
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
        - golangci-lint --version
      script:
        - go test -race -coverpkg ./... -coverprofile=coverage.out ./...

        - golangci-lint run

        - echo "Check that go.mod and go.sum are tidy"
        - go mod tidy
        - if [[ `git status --porcelain go.mod` ]]; then git diff -- go.mod ; echo "go.mod is outdated, please run go mod tidy" ; exit 1; fi
        - if [[ `git status --porcelain go.sum` ]]; then git diff -- go.sum ; echo "go.sum is outdated, please run go mod tidy" ; exit 1; fi
      after_success:
        - bash <(curl -s https://codecov.io/bash)
script:
  - go test -race ./...
